services:
  backend:
    type: web
    env: python
    build:
      workdir: backend
      commands:
        - pip install --no-cache-dir -r requirements.txt
    run:
      workdir: .
      command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - port: 8000
        protocol: http
    envs:
      - key: AI_API_KEY
        value: ${AI_API_KEY}
      - key: GMAIL_USERNAME
        value: ${GMAIL_USERNAME}
      - key: GMAIL_APP_PASSWORD
        value: ${GMAIL_APP_PASSWORD}
      - key: CONTACT_RECIPIENT_EMAIL
        value: ${CONTACT_RECIPIENT_EMAIL}
